services:
  postgis:
    platform: linux/amd64
    image: mdillon/postgis:9.6-alpine
    container_name: postgis
    restart: always
    networks:
      all:
        aliases:
          - all.postgis
    volumes:
      - ../temp/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: hz_9
      POSTGRES_USER: hz_9
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432

networks:
  all:
