services:
  stable-diffusion-webui:
    platform: linux/amd64
    image: universonic/stable-diffusion-webui:minimal
    command: --no-half --no-half-vae --precision full
    runtime: nvidia
    restart: unless-stopped
    ports:
      - "8080:8080/tcp"
    volumes:
      - ../temp/inputs:/app/stable-diffusion-webui/inputs
      - ../temp/textual_inversion_templates:/app/stable-diffusion-webui/textual_inversion_templates
      - ../temp/embeddings:/app/stable-diffusion-webui/embeddings
      - ../temp/extensions:/app/stable-diffusion-webui/extensions
      - ../temp/models:/app/stable-diffusion-webui/models
      - ../temp/localizations:/app/stable-diffusion-webui/localizations
      - ../temp/outputs:/app/stable-diffusion-webui/outputs
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    deploy:
      mode: global
      placement:
        constraints:
          - "node.labels.iface != extern"
      restart_policy:
        condition: unless-stopped
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
